config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions',
 }

 devise_scope :user do
   get '/users/sign_out' => 'public/sessions#destroy'
   get '/users', to: 'public/registrations#new'
 end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: 'admin/sessions'
 }

 devise_scope :admin do
  get '/admin/sign_out', to: 'admin/sessions#destroy', as: 'admin_log_out'
end

devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

 root :to => "public/homes#top"
 get '/admin' => 'admin/homes#top'
 
  namespace :public do
   
   get 'search', to: 'searches#search'
   get 'category_search', to: 'searches#category_search'
   
    resources :rooms do
     resources :comments, only: [:create, :destroy, :index]
     resource :likes, only: [:create, :destroy]

    end

    resources :users, only: [:show, :edit, :update] do
     member do
        get :post
      end
     resources :bookmarks, only: [:create, :destroy, :index]
    end
  end

  namespace :admin do
    resources :categories, only: [:index, :edit, :create, :update]
    resources :rooms, only: [:index, :destroy, :show]
    resources :comments, only: [:destroy, :index]
    resources :users, only: [:index, :edit, :update]

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :room
  
  validates :user_id, uniqueness: { scope: :room_id }
end

app/models/category.rb
class Category < ApplicationRecord
  # バリデーション
  validates :name, presence: true, uniqueness: true
  
  # アソシエーション
  has_many :rooms, through: :room_categories
  has_many :room_categories, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  # バリデーション
  validates :comment, presence: true, length: {maximum: 200 }
  
  # アソシエーション
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  # アソシエーション
  belongs_to :room
  
end

app/models/room.rb
class Room < ApplicationRecord
  # バリデーション
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 300 }
  validates :images, presence: true, length: { maximum: 3 }
  validates :category_ids, presence: true, length: { maximum: 3 }
  # アソシエーション
  belongs_to :user
  has_many :room_categories, dependent: :destroy
  has_many :categories, through: :room_categories
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images


  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists? #①
  end


end

app/models/room_category.rb
class RoomCategory < ApplicationRecord
  belongs_to :room
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
         
  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :email, presence: true, format: { with: /\A[a-zA-Z0-9]{1,}[@][a-zA-Z0-9]{1,}[.][a-zA-Z0-9]{1,}\z/ }, uniqueness: true
  
  has_many :rooms, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_rooms, through: :bookmarks, source: :room
  has_one_attached :profile_image
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
  def log_in(user)
    session[:user_id] = user.id
   self.last_login_at = Time.current
   save
  end
  
  def last_login_time
    if last_login_at
    last_login_at.strftime('%Y-%m-%d %H:%M:%S')
    else
    '未ログイン'
    end
  end 
  
  def after_database_authentication
    self.update_column(:last_login_at, Time.current)
  end
 
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_user_image.jpg'
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @comments = Comment.all.page(params[:page]).per(10)
  end
  
  def destroy
    flash[:success] = "コメントを削除しました。"
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @users = User.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @rooms = Room.all.page(params[:page]).per(10)
  end

  def show
    @room = Room.find(params[:id])
  end

  def destroy
    flash[:success] = "投稿を削除しました。"
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to public_rooms_path
    flash[:success] = "guestuserでログインしました。"
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/comments/index.html.erb
<div class="container">
  <%= render 'layouts/flash'%>
  <div class="row">
    <div class="my-5">
      <table class='table table-hover table-inverse table-light table-fixed' width="100%">
        <thead class="table-dark">
          <tr>
            <th width="10%">投稿者</th>
            <th width="40%">内容</th>
            <th width="20%">コメントした投稿</th>
            <th width="20%">投稿時間</th>
            <th width="10%">削除ボタン</th>
          </tr>
        </thead>
        <tbody>
         <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.user.name %></td>
            <td style="word-wrap:break-word;"><%= comment.comment %></td>
            <td><%= comment.room.title %></td>
            <td><%= comment.created_at.strftime("%Y-%m-%d / %H:%M:%S") %></td>
            <td class="text-center">
              <%= link_to admin_comment_path(comment), method: :delete, class: "btn btn-success btn-sm" do%>
                削除
              <% end %>
            </td>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/rooms/index.html.erb
<div class="container">
  <%= render 'layouts/flash'%>
  <div class="row">
    <div class="my-5">
      <table class='table table-hover table-inverse table-light table-fixed' width="100%">
        <thead class="table-dark">
          <tr>
            <th width="5%">ID</th>
            <th width="10%">投稿者</th>
            <th width="20%">タイトル</th>
            <th width="40%">内容</th>
            <th width="20%">投稿時間</th>
            <th width="5%"></th>
          </tr>
        </thead>
        <tbody>
         <% @rooms.each do |room| %>
          <tr>
            <td><%= room.id %></td>
            <td><%= room.user.name %></td>
            <td style="word-wrap:break-word;">
              <%= link_to admin_room_path(room) do %>
                <%= room.title %>
              <% end %>
            </td>
            <td style="word-wrap:break-word;"><%= room.body %></td>
            <td><%= room.created_at.strftime("%Y-%m-%d / %H:%M:%S") %></td>
            <td class="text-center">
              <%= link_to admin_room_path(room), method: :delete, class: "btn btn-success btn-sm" do%>
                削除
              <% end %>
            </td>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <p>
      <%= paginate @rooms, theme: 'bootstrap-5' %>
    </p>
  </div>

</div>

app/views/admin/rooms/show.html.erb
    <div class="row">
      <div class="col-xl-6 d-flex justify-content-center">
        <div class="ml-5">
          <div class="show_image">
            <% if @room.images.count > 1 %>
              <div id="carouselExampleIndicators" class="carousel slide" data-touch="false">
                <ol class="carousel-indicators">
                  <% @room.images.each_with_index do |image, index| %>
                    <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
                  <% end %>
                </ol>
                <div class="carousel-inner">
                  <% @room.images.each_with_index do |image, index| %>
                    <div class="carousel-item <%= 'active' if index == 0 %>">
                      <%= image_tag image, size: "600x400", class: "bg-white border shadow p-1 m-4" %>
                    </div>
                  <% end %>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">前へ</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">次へ</span>
                </a>
              </div>
            <% else %>
              <%= image_tag @room.images.first, size: "600x400", class: "bg-white border shadow p-1 m-4" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xl-5 d-flex align-items-center">
        <table class="table table-striped bg-white">
          <tr>
            <th class="w-25">タイトル</th>
            <td><%= @room.title %></td>
          </tr>
          <tr>
            <th>投稿者</th>
            <td><%= @room.user.name %></td>
          </tr>
          <tr>
            <th>説明</th>
            <td><%= @room.body %></td>
          </tr>
          <tr>
            <th>投稿日</th>
            <td><%= @room.created_at.strftime("%Y年%m月%d日") %></td>
          </tr>

        </table>
      </div>
    </div>

    <div class="container mt-5">
      <div class="row d-flex justify-content-center">
        <div class="col-9">
          <div class="bg-white rounded shadow-sm">
            <div class="row">
              <div class="col text-center">
                <p class="font-weight-bold">いいね数</p>
                <div>
                  <%= @room.likes.count %>
                </div>
              </div>
              <div class="col text-center">
                <p class="font-weight-bold">マイリスト数</p>
                <div>
                  <%= @room.bookmarks.count %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/admin/users/index.html.erb
<div class="container">
   <%= render 'layouts/flash'%>
  <div class="row">
    <div class="my-5">
      <table class='table table-hover table-inverse table-light table-fixed' width="100%">
        <thead class="table-dark">
          <tr>
            <th width="10%">ID</th>
            <th width="30%">ニックネーム</th>
            <th width="30%">メールアドレス</th>
            <th width="10%">投稿数</th>
            <th width="20%">最終ログイン</th>
          </tr>
        </thead>
        <tbody>
         <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td style="word-wrap:break-word;"><%= user.name %></td>
            <td style="word-wrap:break-word;"><%= user.email %></td>
            <td><%= user.rooms.count %></td>
            <td><%= user.last_login_time %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>