config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions',
 }

 devise_scope :user do
   get '/users/sign_out' => 'public/sessions#destroy'
   get '/users', to: 'public/registrations#new'
 end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: 'admin/sessions'
 }

 devise_scope :admin do
  get '/admin/sign_out', to: 'admin/sessions#destroy', as: 'admin_log_out'
end

devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

 root :to => "public/homes#top"
 get '/admin' => 'admin/homes#top'
 
  namespace :public do
   
   get 'search', to: 'searches#search'
   get 'category_search', to: 'searches#category_search'
   
    resources :rooms do
     resources :comments, only: [:create, :destroy, :index]
     resource :likes, only: [:create, :destroy]

    end

    resources :users, only: [:show, :edit, :update] do
     member do
        get :post
      end
     resources :bookmarks, only: [:create, :destroy, :index]
    end
  end

  namespace :admin do
    resources :categories, only: [:index, :edit, :create, :update]
    resources :rooms, only: [:index, :destroy, :show]
    resources :comments, only: [:destroy, :index]
    resources :users, only: [:index, :edit, :update]

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :room
  
  validates :user_id, uniqueness: { scope: :room_id }
end

app/models/category.rb
class Category < ApplicationRecord
  # バリデーション
  validates :name, presence: true, uniqueness: true
  
  # アソシエーション
  has_many :rooms, through: :room_categories
  has_many :room_categories, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  # バリデーション
  validates :comment, presence: true, length: {maximum: 200 }
  
  # アソシエーション
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  # アソシエーション
  belongs_to :room
  
end

app/models/room.rb
class Room < ApplicationRecord
  # バリデーション
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 300 }
  validates :images, presence: true, length: { maximum: 3 }
  validates :category_ids, presence: true, length: { maximum: 3 }
  # アソシエーション
  belongs_to :user
  has_many :room_categories, dependent: :destroy
  has_many :categories, through: :room_categories
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images


  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists? #①
  end


end

app/models/room_category.rb
class RoomCategory < ApplicationRecord
  belongs_to :room
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
         
  validates :name, presence: true, length: { minimum: 1, maximum: 20 }
  validates :email, presence: true, format: { with: /\A[a-zA-Z0-9]{1,}[@][a-zA-Z0-9]{1,}[.][a-zA-Z0-9]{1,}\z/ }, uniqueness: true
  
  has_many :rooms, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_rooms, through: :bookmarks, source: :room
  has_one_attached :profile_image
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
  def log_in(user)
    session[:user_id] = user.id
   self.last_login_at = Time.current
   save
  end
  
  def last_login_time
    if last_login_at
    last_login_at.strftime('%Y-%m-%d %H:%M:%S')
    else
    '未ログイン'
    end
  end 
  
  def after_database_authentication
    self.update_column(:last_login_at, Time.current)
  end
 
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_user_image.jpg'
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @comments = Comment.all.page(params[:page]).per(10)
  end
  
  def destroy
    flash[:success] = "コメントを削除しました。"
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @users = User.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @rooms = Room.all.page(params[:page]).per(10)
  end

  def show
    @room = Room.find(params[:id])
  end

  def destroy
    flash[:success] = "投稿を削除しました。"
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<li class="nav-item">
  <div class="nav-link">
    <%= link_to  admin_path do %>
      <i class="fa-solid fa-user"></i> ユーザー
    <% end %>
  </div>
</li>

<li class="nav-item">
  <div class="nav-link">
    <%= link_to admin_rooms_path do %>
      <i class="fa-solid fa-couch"></i> 投稿
    <% end %>
  </div>
</li>

<li class="nav-item">
  <div class="nav-link">
    <%= link_to  admin_comments_path do %>
      <i class="fa-regular fa-message"></i> コメント
    <% end %>
  </div>
</li>

<li class="nav-item">
  <div class="nav-link">
    <%= link_to  admin_categories_path do %>
      <i class="fa-solid fa-tag"></i> カテゴリー
    <% end %>
  </div>
</li>

<li class="nav-item">
  <div class="nav-link">
    <%= link_to admin_log_out_path, method: :delete do %>
      <i class="fa-solid fa-arrow-right-from-bracket"></i> ログアウト
    <% end %>
  </div>
</li>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
 	<div class="alert alert-<%= name %>">
    	<%= msg %>
  </div>
<% end %>

app/views/layouts/_header.erb
<header class="shadow">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      
      <div class="navbar-brand">
        <%= link_to  root_path do %>
          <%= image_tag 'heyamoyou_logo.jpg', size: "280x70" %>
        <% end %>
      </div>
                  
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbar-header">
        <ul class="navbar-nav mr-auto">
          <% if admin_signed_in? %>
                <%= render 'layouts/admin_header' %>
          <% elsif user_signed_in? %>
          
            <li class="nav-item dropdown">
              <div class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <a href="#">マイページ</a>
              </div>
                  
              <div class="dropdown-menu">
                <div class="dropdown-item">
                  <%= link_to public_user_path(current_user) do %>
                    マイページ
                  <% end %>
                </div>
                <% if current_user.email == "guest@example.com" %>
                  <a class="dropdown-item disabled">
                    マイリスト
                  </a>
                <% else %>
                  <div class="dropdown-item">
                    <%= link_to  public_user_bookmarks_path(current_user) do %>
                      マイリスト
                    <% end %>
                  </div>
                <% end %>
              </div>
            </li>
            
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to  public_rooms_path do %>
                    投稿一覧
                 <% end %>
               </div>
            </li>
            
            <li class="nav-item">
              <% if current_user.email == "guest@example.com" %>
                <a class="nav-link disabled">
                  投稿する
                </a>
              <% else %>
                <div class="nav-link">
                  <%= link_to  new_public_room_path do %>
                    投稿する
                  <% end %> 
                </div>
              <% end %>
            </li>
            
            <li class="nav-item active">
              <div class="nav-link">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  ログアウト
                <% end %>
              </div>
            </li>
            
          <% else %>
          
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to new_user_registration_path do %>
                  新規登録
                <% end %>
              </div>
            </li>
            
            <li class="nav-item">
              <div class="nav-link">
                <%= link_to new_user_session_path do %>
                  ログイン
                <% end %>
              </div>
            </li>
            
          <% end %>
          
        </ul>
        
        <form class="form-inline my-2 my-md-0">
          <input class="form-control mr-sm-2" type="search" placeholder="検索..." aria-label="検索...">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
        </form>
        
      </div>
    </nav>
  </div>

</header>

app/views/layouts/_header.html.erb
<header class="shadow">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

      <div class="navbar-brand">
        <%= link_to  root_path do %>
          <%= image_tag 'heyamoyou_logo.png', size: "140x45" %>
        <% end %>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar-header">
        <ul class="navbar-nav mr-auto">
          <% if admin_signed_in? %>

            <%= render 'layouts/admin_header' %>

          <% elsif user_signed_in? %>

            <li class="nav-item dropdown">
              <div class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <a href="#"><i class="fa-solid fa-user"></i> マイページ</a>
              </div>

              <div class="dropdown-menu">
                <div class="dropdown-item">
                  <%= link_to public_user_path(current_user) do %>
                    <i class="fa-solid fa-user"></i> マイページ
                  <% end %>
                </div>
                <% if current_user.email == "guest@example.com" %>
                  <a class="dropdown-item disabled">
                    <i class="fa-solid fa-newspaper"></i> 投稿記事
                  </a>
                  <a class="dropdown-item disabled">
                    <i class="fa-solid fa-folder"></i> マイリスト
                  </a>
                <% else %>
                  <div class="dropdown-item">
                    <%= link_to  post_public_user_path(current_user) do %>
                      <i class="fa-solid fa-newspaper"></i> 投稿記事
                    <% end %>
                  </div>
                  <div class="dropdown-item">
                    <%= link_to  public_user_bookmarks_path(current_user) do %>
                      <i class="fa-solid fa-folder"></i> マイリスト
                    <% end %>
                  </div>
                <% end %>
              </div>
            </li>

            <li class="nav-item">
              <div class="nav-link">
                <%= link_to  public_rooms_path do %>
                    <i class="fa-solid fa-couch"></i> 投稿一覧
                 <% end %>
               </div>
            </li>

            <li class="nav-item">
              <% if current_user.email == "guest@example.com" %>
                <a class="nav-link disabled">
                  <i class="fa-solid fa-pen-fancy"></i> 投稿する
                </a>
              <% else %>
                <div class="nav-link">
                  <%= link_to  new_public_room_path do %>
                    <i class="fa-solid fa-pen-fancy"></i> 投稿する
                  <% end %>
                </div>
              <% end %>
            </li>

            <li class="nav-item active">
              <div class="nav-link">
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa-solid fa-arrow-right-from-bracket"></i> ログアウト
                <% end %>
              </div>
            </li>

          <% else %>

            <li class="nav-item">
              <div class="nav-link">
                <%= link_to new_user_registration_path do %>
                  <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </div>
            </li>

            <li class="nav-item">
              <div class="nav-link">
                <%= link_to new_user_session_path do %>
                  <i class="fa-solid fa-arrow-right-to-bracket"></i> ログイン
                <% end %>
              </div>
            </li>

          <% end %>

        </ul>

        <div class="form-inline my-2 my-md-0">
          <%= form_with url: public_search_path, method: :get, local: true do |f| %>
            <%= f.text_field :query, placeholder: "検索...", class: "form-control mr-sm-2" %>
            <%= f.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
        </div>

      </div>
    </nav>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>へやもよう</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/76a51096e2.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'custom' %>
  </head>

  <body style= "background-color: #F2E9D9;">
    
    <div style="padding-top:71px">
      <%= render 'layouts/header' %>
    </div>
    
    <%= yield %>
  </body>
</html>